jpedroschmitz/rocketdocs

examples/gatsby-theme-docs/gatsby-config.js
examples/gatsby-theme-docs/package.json
examples/gatsby-theme-docs/src/docs/getting-started.mdx
examples/gatsby-theme-docs/src/docs/usage/navigation.mdx
examples/gatsby-theme-docs/src/docs/usage/shadowing.mdx
examples/gatsby-theme-docs/src/pages/404.js
yarn.lock

chore(examples): Update theme-docs dependency

---

@rocketseat/gatsby-theme-docs/package.json
@rocketseat/gatsby-theme-docs/src/components/Docs/TOC/styles.js
@rocketseat/gatsby-theme-docs/src/components/Layout/index.js
@rocketseat/gatsby-theme-docs/src/components/Layout/styles.js
@rocketseat/gatsby-theme-docs/src/styles/global.js

Change styles for blockquote and table of contents

chore: Update TOC styles and blockquote

---

@rocketseat/gatsby-theme-docs-core/gatsby-node.js
@rocketseat/gatsby-theme-docs-core/package.json
@rocketseat/gatsby-theme-docs/package.json
examples/gatsby-theme-docs/package.json

This PR fixes two issues (#13 and #17).

fix: #13 and #17

---

examples/gatsby-theme-docs/src/docs/getting-started.mdx

typo error fix

---

@rocketseat/gatsby-theme-docs/package.json
@rocketseat/gatsby-theme-docs/src/components/Docs/TOC/index.js
examples/gatsby-theme-docs/README.md
examples/gatsby-theme-docs/gatsby-config.js

Fixes issue on 2.2.0 caused by PropTypes
Also updated the example to match the latest version

chore: release 2.2.1

---

@rocketseat/gatsby-theme-docs/gatsby/wrapPageElement.js
@rocketseat/gatsby-theme-docs/package.json

Removed console.log from build

chore: release 2.2.3

---

examples/gatsby-theme-docs/README.md
examples/gatsby-theme-docs/gatsby-config.js
examples/gatsby-theme-docs/package.json
examples/gatsby-theme-docs/src/@rocketseat/gatsby-theme-docs/text/index.mdx
examples/gatsby-theme-docs/src/config/sidebar.yml
examples/gatsby-theme-docs/src/docs/changelog.mdx
examples/gatsby-theme-docs/src/docs/faq.mdx
examples/gatsby-theme-docs/src/docs/getting-started.mdx
examples/gatsby-theme-docs/src/docs/usage/creating-docs.mdx
examples/gatsby-theme-docs/src/docs/usage/navigation.mdx
examples/gatsby-theme-docs/src/docs/usage/shadowing.mdx
yarn.lock

chore(examples): update documentation

---

examples/gatsby-theme-docs/gatsby-config.js
examples/gatsby-theme-docs/package.json
examples/gatsby-theme-docs/src/docs/usage/creating-docs.mdx
yarn.lock

Adds `gatsby-plugin-remove-trailing-slashes`, trying to fix issue

chore: remove trailing slashes

---

examples/gatsby-theme-docs/src/docs/faq.mdx

Adding an example theme usage link to [Botmation](https://botmation.dev)
Currently, I'm prepping a [new release](https://github.com/mrWh1te/botmation-docs/pull/23) of the Botmation docs site with the latest version of your theme. Really like it!

Example Theme Usage - Botmation

---

@rocketseat/gatsby-theme-docs/package.json
@rocketseat/gatsby-theme-docs/src/components/Docs/TOC/styles.js
@rocketseat/gatsby-theme-docs/src/components/Layout/styles.js
@rocketseat/gatsby-theme-docs/src/styles/global.js
examples/gatsby-theme-docs/package.json
examples/gatsby-theme-docs/src/docs/usage/creating-docs.mdx
examples/gatsby-theme-docs/src/docs/usage/shadowing.mdx
yarn.lock

This PR fixes some issues and enhance the documentation;
Fixes #40;

fix: issue with the new JSX transform

---

examples/gatsby-theme-docs/package.json

Updates @rocketseat/gatsby-theme-docs to latest version for example
n/a

chore: bump package version for example

---

@rocketseat/gatsby-theme-docs/src/text/index.mdx

Fixes a spelling error on the index page.

fix: Corrected spelling error

---

.github/workflows/release.yml

Another try to fix the workflow error
n/a

ci: adjust commit message

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/question.md
@rocketseat/gatsby-theme-docs-core/README.md
@rocketseat/gatsby-theme-docs/README.md
@rocketseat/gatsby-theme-docs/gatsby-config.js
README.md
examples/gatsby-theme-docs/README.md
examples/gatsby-theme-docs/gatsby-config.js
examples/gatsby-theme-docs/src/docs/usage/creating-docs.mdx

This PR updates the documentation, fixing and updating links, and adding a new section on the readme.
I've also updated the contributing guides to keep them up-to-date.
n/a

docs: update contributing guides, add credits and fix broken links

---

.changeset/metal-boxes-cry.md

Changeset for `@rocketseat/gatsby-theme-docs`
n/a

chore: create changeset for 2.3.1

---

.changeset/thirty-grapes-whisper.md
@rocketseat/gatsby-theme-docs-core/util/with-default.js

Adds changeset so we can release #93 and #98.

chore: add changeset

---

.changeset/serious-parents-run.md
@rocketseat/gatsby-theme-docs/package.json

chore: bump core package version

---

.changeset/pretty-panthers-rest.md
yarn.lock

#34 and #86 didn't have any changeset. This PR adds it.
n/a

chore: add changeset and update yarn.lock

---

.changeset/angry-horses-exist.md
.changeset/twenty-rats-fry.md
examples/gatsby-theme-docs/src/@rocketseat/gatsby-theme-docs/text/index.mdx
examples/gatsby-theme-docs/src/docs/faq.mdx
examples/gatsby-theme-docs/src/docs/getting-started.mdx

docs: mention that the theme supports gatsby 4

---

.github/workflows/publish-starters.yml

ci: use node 14 on publish starters action

---

.github/workflows/commit.yml
.github/workflows/lint.yml
.github/workflows/publish-starters.yml
.github/workflows/release.yml

ci: use lts as the node.js version

---

@rocketseat/gatsby-theme-docs-core/package.json
@rocketseat/gatsby-theme-docs/package.json
examples/gatsby-theme-docs/package.json

This way we can release it as version 4 on #153, instead of 5.

chore: change version back to 3.2.0
